<?php
namespace MOC\MocMessageQueue\Message;

abstract class AbstractMessage {

	/**
	 * @var string
	 */
	protected $identifer;

	/**
	 * Return a unique identifer for this message
	 *
	 * @return string
	 */
	public function getIdentifier() {
		return $this->identifer;
	}

	/**
	 * Set the unique identifier for this message.
	 *
	 * The ID is typically generated by the actual messagequeue implementation, and it needs to be able to set the
	 * id on the message.
	 *
	 * @param string $identifer
	 * @return boid
	 */
	public function setIdentifier($identifer) {
		$this->identifer = $identifer;
	}

}
