<?php
namespace MOC\MocMessageQueue\Message;

interface MessageInterface {

	/**
	 * Return a unique identifer for this message
	 *
	 * @return string
	 */
	public function getIdentifier();

	/**
	 * Set the unique identifier for this message.
	 *
	 * The ID is typically generated by the actual messagequeue implementation, and it needs to be able to set the
	 * id on the message.
	 *
	 * @param string $identifer
	 * @return void
	 */
	public function setIdentifier($identifer);
}