<?php
namespace MOC\MocMessageQueue\Message;

class StringMessage implements MessageInterface {

	/**
	 * @var string
	 */
	protected $payload;

	/**
	 * @var string
	 */
	protected $identifer;

	/**
	 * @param $payload
	 */
	public function __construct($payload) {
		$this->payload = $payload;
	}

	/**
	 * Return a unique identifer for this message
	 *
	 * @return string
	 */
	public function getIdentifier() {
		return $this->identifer;
	}

	/**
	 * Set the unique identifier for this message.
	 *
	 * The ID is typically generated by the actual messagequeue implementation, and it needs to be able to set the
	 * id on the message.
	 *
	 * @param string $identifer
	 * @return boid
	 */
	public function setIdentifier($identifer) {
		$this->identifer = $identifer;
	}

	/**
	 * @return string
	 */
	public function getPayload() {
		return $this->payload;
	}

}
